### ISSUE TITLE
Node example SSL Error

### ISSUE THREAD

**Issue by Harjot1Singh** [fsouza/fake-gcs-server#311]
When trying the example in node 10.16.0: `Error: error:09091064:PEM routines:PEM_read_bio_ex:bad base64 decode`.

I'm unable to get it to work. Any ideas? I assume it's something to do with SSL. I'm on Mac.

Trace
```
uploads_1        | [test ]     error:09091064:PEM routines:PEM_read_bio_ex:bad base64 decode
uploads_1        | [test ] 
uploads_1        | [test ]       at Object.sign (node_modules/jwa/index.js:152:45)
uploads_1        | [test ]       at Object.jwsSign [as sign] (node_modules/jws/lib/sign-stream.js:32:24)
uploads_1        | [test ]       at GoogleToken.requestToken (node_modules/gtoken/build/src/index.js:197:31)
uploads_1        | [test ]       at GoogleToken.getTokenAsync (node_modules/gtoken/build/src/index.js:136:21)
uploads_1        | [test ]       at GoogleToken.getToken (node_modules/gtoken/build/src/index.js:78:21)
uploads_1        | [test ]       at JWT.refreshTokenNoCache (node_modules/google-auth-library/build/src/auth/jwtclient.js:148:36)
uploads_1        | [test ]       at JWT.refreshToken (node_modules/google-auth-library/build/src/auth/oauth2client.js:150:24)
uploads_1        | [test ]       at JWT.getRequestMetadataAsync (node_modules/google-auth-library/build/src/auth/oauth2client.js:259:28)
uploads_1        | [test ]       at JWT.getRequestMetadataAsync (node_modules/google-auth-library/build/src/auth/jwtclient.js:81:26)
```

**Comment by Harjot1Singh** [comment]
I think this might be more related to Docker/module installation. Will investigate further, because I can get it to work if I don't run the example in a Docker container.

**Comment by Harjot1Singh** [comment]
For anyone who encounters this, do not supply a dummy `GOOGLE_APPLICATION_CREDENTIALS` environment variable. The `@google-cloud/storage` will attempt to use it.

Completely unrelated to the fake gcs server :)
